"""empty message

Revision ID: 103e2b3bcf6f
Revises: a6300b419b2c
Create Date: 2021-05-06 01:08:55.752045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e2b3bcf6f'
down_revision = 'a6300b419b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
