"""empty message

Revision ID: 114b646cfb92
Revises: beb626c47893
Create Date: 2021-05-05 18:43:54.313991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114b646cfb92'
down_revision = 'beb626c47893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
