"""empty message

Revision ID: 20d202f33934
Revises: 7257f0332ef6
Create Date: 2021-05-04 23:41:24.670002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20d202f33934'
down_revision = '7257f0332ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.drop_index('ix_users_用户名', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', '用户名')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('用户名', mysql.VARCHAR(length=20), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_用户名', 'users', ['用户名'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
