"""empty message

Revision ID: 78b9a96f0316
Revises: 103e2b3bcf6f
Create Date: 2021-05-06 01:10:25.479945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b9a96f0316'
down_revision = '103e2b3bcf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
