"""empty message

Revision ID: a6300b419b2c
Revises: 114b646cfb92
Create Date: 2021-05-06 00:46:02.131146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6300b419b2c'
down_revision = '114b646cfb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
