"""base model

Revision ID: a1406d33322c
Revises: 
Create Date: 2021-09-30 15:31:37.623117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a1406d33322c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=40), nullable=True, comment='邮箱'),
    sa.Column('password', sa.String(length=102), nullable=False, comment='密码'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='激活状态'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='管理员状态'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('article',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('views', sa.Integer(), nullable=True, comment='浏览量'),
    sa.Column('likes', sa.Integer(), nullable=True, comment='点赞量'),
    sa.Column('collects', sa.Integer(), nullable=True, comment='收藏量'),
    sa.Column('shares', sa.Integer(), nullable=True, comment='分享量'),
    sa.Column('is_delete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_category_id'), 'article', ['category_id'], unique=False)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_table('article_link_tag',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id', 'article_id', 'tag_id')
    )
    op.create_index(op.f('ix_article_link_tag_article_id'), 'article_link_tag', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_link_tag_id'), 'article_link_tag', ['id'], unique=False)
    op.create_index(op.f('ix_article_link_tag_tag_id'), 'article_link_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_link_tag_tag_id'), table_name='article_link_tag')
    op.drop_index(op.f('ix_article_link_tag_id'), table_name='article_link_tag')
    op.drop_index(op.f('ix_article_link_tag_article_id'), table_name='article_link_tag')
    op.drop_table('article_link_tag')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_article_category_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
